switch:
- name: Audio Power
  unique_id: villa_a1_audio_power
  address: 1/1/202
  state_address: 1/1/203
- name: Audio Mute
  unique_id: villa_a1_audio_mute
  address: 1/1/220
- name: Audio Play/Pause
  unique_id: villa_a1_audio_play_pause
  address: 1/1/222
- name: Audio Next/Prev
  unique_id: villa_a1_audio_next_prev
  address: 1/1/226
light:
- name: Audio Absolut volume
  unique_id: villa_a1_audio_absolut_volume
  brightness_address: 1/1/211
sensor:
- name: Audio Track name
  unique_id: villa_a1_audio_track_name_string88591
  type: string88591
  state_address: 1/1/231
- name: Audio Playlist Select
  unique_id: villa_a1_audio_playlist_select_major_5_x
  type: major.5.x
  state_address: 1/1/239
