knx:
  switch:
  - name: Audio Power
    address: 1/1/202
    state_address: 1/1/203
  - name: Audio Mute
    address: 1/1/220
  - name: Audio Play/Pause
    address: 1/1/222
  light:
  - name: Audio Absolut volume
    address: 1/1/202
    brightness_address: 1/1/211
  button:
  - name: Audio Next/Prev
    address: 1/1/226
  sensor:
  - name: Audio Track name
    type: latin_1
    state_address: 1/1/231
  number:
  - name: Audio Playlist Select
    address: 1/1/239
    type: 1byte_unsigned
media_player:
- platform: universal
  name: Villa A1 Audio
  unique_id: villa_a1_audio_module
  commands:
    turn_on:
      action: switch.turn_on
      target:
        entity_id: switch.audio_power
    turn_off:
      action: switch.turn_off
      target:
        entity_id: switch.audio_power
    media_play:
      action: switch.turn_on
      target:
        entity_id: switch.audio_play_pause
    media_pause:
      action: switch.turn_off
      target:
        entity_id: switch.audio_play_pause
    media_next_track:
      action: button.press
      target:
        entity_id: button.audio_next_prev
    volume_mute:
      action: switch.toggle
      target:
        entity_id: switch.audio_mute
    volume_set:
      action: light.turn_on
      target:
        entity_id: light.audio_absolut_volume
      data:
        brightness_pct: '{{ (volume_level * 100) | round(0) }}'
    select_source:
      action: number.set_value
      target:
        entity_id: number.audio_playlist_select
      data:
        value: '{{ source }}'
  attributes:
    is_volume_muted: switch.audio_mute
    volume_level: light.audio_absolut_volume|brightness
    media_title: sensor.audio_track_name
    source: number.audio_playlist_select
  state_template: "{% if is_state('switch.audio_power', 'off') %}\n  off\n{% elif\
    \ is_state('switch.audio_play_pause', 'on') %}\n  playing\n{% else %}\n  idle\n\
    {% endif %}"
